In [3]:
import pandas as pd

prices=[2999, 15999, 52999, 4999, 1999]
products=["Wireless Earbuds", "Smartphone", "Laptop", "Smartwatch", "Bluetooth Speaker"]
product_prices = pd.Series(prices,index=products)
print(product_prices)

Wireless Earbuds      2999
Smartphone           15999
Laptop               52999
Smartwatch            4999
Bluetooth Speaker     1999
dtype: int64

In [ ]:
print("Mean:", product_prices.mean())

Mean: 15799.0

In [ ]:
print("Sum:", product_prices.sum())

Sum: 78995

In [ ]:
print("Head (First 3 Element):\n", product_prices.head(3))

Head (First 3 Element):
 Wireless Earbuds     2999
Smartphone          15999
Laptop              52999
dtype: int64

In [ ]:
print("Tail (Last 2 Element):\n", product_prices.tail(2))

Tail (Last 2 Element):
 Smartwatch           4999
Bluetooth Speaker    1999
dtype: int64

In [ ]:
print("apply (Adding 18% GST):\n", product_prices.apply(lambda x: f'₹{x+(x*0.18)}'))

apply (Adding 18% GST):
 Wireless Earbuds     ₹3538.8199999999997
Smartphone                     ₹18878.82
Laptop                         ₹62538.82
Smartwatch                      ₹5898.82
Bluetooth Speaker               ₹2358.82
dtype: object

In [ ]:
print("Map (Formating as Currency):\n", product_prices.map(lambda x: f"₹{x}.00"))

Map (Formating as Currency):
 Wireless Earbuds      ₹2999.00
Smartphone           ₹15999.00
Laptop               ₹52999.00
Smartwatch            ₹4999.00
Bluetooth Speaker     ₹1999.00
dtype: object

In [ ]:
print(product_prices.sort_values())

Bluetooth Speaker     1999
Wireless Earbuds      2999
Smartwatch            4999
Smartphone           15999
Laptop               52999
dtype: int64

In [ ]:
print(product_prices.sort_index())

Bluetooth Speaker     1999
Laptop               52999
Smartphone           15999
Smartwatch            4999
Wireless Earbuds      2999
dtype: int64

In [ ]:
print(product_prices.sort_index(ascending=False))

Wireless Earbuds      2999
Smartwatch            4999
Smartphone           15999
Laptop               52999
Bluetooth Speaker     1999
dtype: int64

In [ ]:
print(product_prices.value_counts())

2999     1
15999    1
52999    1
4999     1
1999     1
Name: count, dtype: int64

In [4]:
import pandas as pd

data = {
"Products": ["Wireless Earbuds", "Smartphone", "Laptop", "Smartwatch", "Bluetooth Speaker"],
"Brand": ["SundMax", "TechNova", "ByteCore", "TimeTrack", "EchoBoom"],
"Prices": [2999, 15999, 52999, 4999, 1999],
"Stock": [50, 30, 20, 40, 60],
"BestSeller": [True,False,False,True,True]
}
df = pd.DataFrame(data)
print(df)

            Products      Brand  Prices  Stock  BestSeller
0   Wireless Earbuds    SundMax    2999     50        True
1         Smartphone   TechNova   15999     30       False
2             Laptop   ByteCore   52999     20       False
3         Smartwatch  TimeTrack    4999     40        True
4  Bluetooth Speaker   EchoBoom    1999     60        True

In [ ]:
print(df.shape)
print(df.columns)
print(df.info())

(5, 5)
Index(['Products', 'Brand', 'Prices', 'Stock', 'BestSeller'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Products    5 non-null      object
 1   Brand       5 non-null      object
 2   Prices      5 non-null      int64
 3   Stock       5 non-null      int64
 4   BestSeller  5 non-null      bool
dtypes: bool(1), int64(2), object(2)
memory usage: 297.0+ bytes
None

In [ ]:
print(df.head(3))
print(df.tail(2))

           Products     Brand  Prices  Stock  BestSeller
0  Wireless Earbuds   SundMax    2999     50        True
1        Smartphone  TechNova   15999     30       False
2            Laptop  ByteCore   52999     20       False
            Products      Brand  Prices  Stock  BestSeller
3         Smartwatch  TimeTrack    4999     40        True
4  Bluetooth Speaker   EchoBoom    1999     60        True

In [ ]:
print(df)
print(df.loc[4,"Products"])
print(df.loc[4,"Products"])
print(df.loc[4,"Stock"])

print(df.iloc[4, 0])
print(df.iloc[2, 1])
print(df.iloc[3, 3])

            Products      Brand  Prices  Stock  BestSeller
0   Wireless Earbuds    SundMax    2999     50        True
1         Smartphone   TechNova   15999     30       False
2             Laptop   ByteCore   52999     20       False
3         Smartwatch  TimeTrack    4999     40        True
4  Bluetooth Speaker   EchoBoom    1999     60        True
Bluetooth Speaker
Bluetooth Speaker
60
Bluetooth Speaker
ByteCore
40

In [ ]:
print(df.iloc[3])
print(df.iloc[2])

Products      Smartwatch
Brand          TimeTrack
Prices              4999
Stock                 40
BestSeller          True
Name: 3, dtype: object
Products        Laptop
Brand         ByteCore
Prices           52999
Stock               20
BestSeller       False
Name: 2, dtype: object

In [ ]:
print(df)
print(df.loc[df['BestSeller']==True])
print(df.loc[df['Stock']<40])
print(df.loc[df['Prices']<1000])

            Products      Brand  Prices  Stock  BestSeller
0   Wireless Earbuds    SundMax    2999     50        True
1         Smartphone   TechNova   15999     30       False
2             Laptop   ByteCore   52999     20       False
3         Smartwatch  TimeTrack    4999     40        True
4  Bluetooth Speaker   EchoBoom    1999     60        True
            Products      Brand  Prices  Stock  BestSeller
0   Wireless Earbuds    SundMax    2999     50        True
3         Smartwatch  TimeTrack    4999     40        True
4  Bluetooth Speaker   EchoBoom    1999     60        True
     Products     Brand  Prices  Stock  BestSeller
1  Smartphone  TechNova   15999     30       False
2      Laptop  ByteCore   52999     20       False
Empty DataFrame
Columns: [Products, Brand, Prices, Stock, BestSeller]
Index: []

In [ ]:
 df_renamed = df.rename(columns={"Price": "Cost"})
 print(df_renamed)

            Products      Brand  Prices  Stock  BestSeller
0   Wireless Earbuds    SundMax    2999     50        True
1         Smartphone   TechNova   15999     30       False
2             Laptop   ByteCore   52999     20       False
3         Smartwatch  TimeTrack    4999     40        True
4  Bluetooth Speaker   EchoBoom    1999     60        True

In [ ]:
df_grouped = df.groupby("Brand").agg({"Prices": "sum", "Stock": "sum"})
print(df_grouped)

           Prices  Stock
Brand
ByteCore    52999     20
EchoBoom     1999     60
SundMax      2999     50
TechNova    15999     30
TimeTrack    4999     40

In [ ]:
grouped=df.groupby("Brand").agg({"Prices": ["mean", "max", "min"]})
print(grouped)

            Prices
              mean    max    min
Brand
ByteCore   52999.0  52999  52999
EchoBoom    1999.0   1999   1999
SundMax     2999.0   2999   2999
TechNova   15999.0  15999  15999
TimeTrack   4999.0   4999   4999

In [ ]:
grouped = df.groupby("Brand")["Prices"].mean()
print(grouped)

Brand
ByteCore     52999.0
EchoBoom      1999.0
SundMax       2999.0
TechNova     15999.0
TimeTrack     4999.0
Name: Prices, dtype: float64

In [ ]:
data2 = {
    "Brand": ["SundMax", "TechNova", "ByteCore", "TimeTrack", "EchoBoom"],
    "Rating": [4.2, 4.5, 4.0, 4.1, 3.9],
    'discount': [28,40,16,10,5]
}
df_rating = pd.DataFrame(data2)
print(df_rating)

       Brand  Rating  discount
0    SundMax     4.2        28
1   TechNova     4.5        40
2   ByteCore     4.0        16
3  TimeTrack     4.1        10
4   EchoBoom     3.9         5

In [ ]:
df_merged = df.merge(df_rating, on="Brand")
print("Merged DataFrame (Adding Rating):\n", df_merged)

Merged DataFrame (Adding Rating):
             Products      Brand  Prices  Stock  BestSeller  Rating  discount
0   Wireless Earbuds    SundMax    2999     50        True     4.2        28
1         Smartphone   TechNova   15999     30       False     4.5        40
2             Laptop   ByteCore   52999     20       False     4.0        16
3         Smartwatch  TimeTrack    4999     40        True     4.1        10
4  Bluetooth Speaker   EchoBoom    1999     60        True     3.9         5

In [ ]:
new_data = {
    "Products": ["Tablet"],
    "Brand": ["SmartWare"],
    "Price": [12999],
    "Stock": [25],
    "BestSeller": [True]
}
df_new = pd.DataFrame(new_data)
print(df_new)

  Products      Brand  Price  Stock  BestSeller
0   Tablet  SmartWare  12999     25        True

In [ ]:
df_concat = pd.concat([df, df_new], ignore_index=True)
print(df_concat)

            Products      Brand   Prices  Stock  BestSeller    Price
0   Wireless Earbuds    SundMax   2999.0     50        True      NaN
1         Smartphone   TechNova  15999.0     30       False      NaN
2             Laptop   ByteCore  52999.0     20       False      NaN
3         Smartwatch  TimeTrack   4999.0     40        True      NaN
4  Bluetooth Speaker   EchoBoom   1999.0     60        True      NaN
5             Tablet  SmartWare      NaN     25        True  12999.0

In [ ]:
print(df["Products"])

0     Wireless Earbuds
1           Smartphone
2               Laptop
3           Smartwatch
4    Bluetooth Speaker
Name: Products, dtype: object

In [ ]:
print(df[["Products", "Prices", "Stock"]])

            Products  Prices  Stock
0   Wireless Earbuds    2999     50
1         Smartphone   15999     30
2             Laptop   52999     20
3         Smartwatch    4999     40
4  Bluetooth Speaker    1999     60

In [ ]:
df["Prices"] = df["Prices"].astype(float)
print(df)

            Products      Brand   Prices  Stock  BestSeller
0   Wireless Earbuds    SundMax   2999.0     50        True
1         Smartphone   TechNova  15999.0     30       False
2             Laptop   ByteCore  52999.0     20       False
3         Smartwatch  TimeTrack   4999.0     40        True
4  Bluetooth Speaker   EchoBoom   1999.0     60        True

In [ ]:
df["Rank"] = df["Prices"].rank(ascending=False)
print(df)
print(df.sort_values(by="Rank", ascending=True))
print(df.sort_values(by="Rank", ascending=False))

            Products      Brand   Prices  Stock  BestSeller  Rank
0   Wireless Earbuds    SundMax   2999.0     50        True   4.0
1         Smartphone   TechNova  15999.0     30       False   2.0
2             Laptop   ByteCore  52999.0     20       False   1.0
3         Smartwatch  TimeTrack   4999.0     40        True   3.0
4  Bluetooth Speaker   EchoBoom   1999.0     60        True   5.0
            Products      Brand   Prices  Stock  BestSeller  Rank
2             Laptop   ByteCore  52999.0     20       False   1.0
1         Smartphone   TechNova  15999.0     30       False   2.0
3         Smartwatch  TimeTrack   4999.0     40        True   3.0
0   Wireless Earbuds    SundMax   2999.0     50        True   4.0
4  Bluetooth Speaker   EchoBoom   1999.0     60        True   5.0
            Products      Brand   Prices  Stock  BestSeller  Rank
4  Bluetooth Speaker   EchoBoom   1999.0     60        True   5.0
0   Wireless Earbuds    SundMax   2999.0     50        True   4.0
3         Smartwatch  TimeTrack   4999.0     40        True   3.0
1         Smartphone   TechNova  15999.0     30       False   2.0
2             Laptop   ByteCore  52999.0     20       False   1.0

In [5]:
import pandas as pd
df1 = pd.DataFrame({
    "ID": [1, 2],
    "Name": ["Alice", "Bob"],
    "Age": [25, 30]
})

df2 = pd.DataFrame({
    "ID": [3, 4],
    "Name": ["Charlie", "David"],
    "Age": [28, 35]
})

df_combined = pd.concat([df1, df2], axis=0)
print(df_combined)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
0   3  Charlie   28
1   4    David   35

In [6]:
df_combined = pd.concat([df1, df2], axis=1)
print(df_combined)

   ID   Name  Age  ID     Name  Age
0   1  Alice   25   3  Charlie   28
1   2    Bob   30   4    David   35

In [7]:
import pandas as pd
print(df)
df.pivot_table(values="Prices", index="Brand", columns="Stock", aggfunc="max")

            Products      Brand  Prices  Stock  BestSeller
0   Wireless Earbuds    SundMax    2999     50        True
1         Smartphone   TechNova   15999     30       False
2             Laptop   ByteCore   52999     20       False
3         Smartwatch  TimeTrack    4999     40        True
4  Bluetooth Speaker   EchoBoom    1999     60        True

Stock           20       30      40      50      60
Brand
ByteCore   52999.0      NaN     NaN     NaN     NaN
EchoBoom       NaN      NaN     NaN     NaN  1999.0
SundMax        NaN      NaN     NaN  2999.0     NaN
TechNova       NaN  15999.0     NaN     NaN     NaN
TimeTrack      NaN      NaN  4999.0     NaN     NaN

In [8]:
pd.crosstab(df["Brand"], df["Stock"])

Stock      20  30  40  50  60
Brand
ByteCore    1   0   0   0   0
EchoBoom    0   0   0   0   1
SundMax     0   0   0   1   0
TechNova    0   1   0   0   0
TimeTrack   0   0   1   0   0

In [9]:
import numpy as np

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, np.nan, 5],
    'C': [10, np.nan, np.nan, 40, 40]
}
df = pd.DataFrame(data)
print("Original DataFrame with Missing Values:")
print(df)

Original DataFrame with Missing Values:
     A    B     C
0  1.0  NaN  10.0
1  2.0  2.0   NaN
2  NaN  3.0   NaN
3  4.0  NaN  40.0
4  5.0  5.0  40.0

In [10]:
df_dropna = df.dropna()
print("\nDataFrame after dropping rows with missing values:")
print(df_dropna)

DataFrame after dropping rows with missing values:
     A    B     C
4  5.0  5.0  40.0

In [15]:
df_fillna = df.fillna(0)
print(df_fillna)

     A    B     C
0  1.0  0.0  10.0
1  2.0  2.0   0.0
2  0.0  3.0   0.0
3  4.0  0.0  40.0
4  5.0  5.0  40.0

In [16]:
df_interpolate = df.interpolate()
print("\nDataFrame after filling NaN values using interpolation:")
print(df_interpolate)

DataFrame after filling NaN values using interpolation:
     A    B     C
0  1.0  NaN  10.0
1  2.0  2.0  20.0
2  3.0  3.0  30.0
3  4.0  4.0  40.0
4  5.0  5.0  40.0

In [22]:
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv

In [23]:
import pandas as pd

df = pd.read_csv("emails.csv")
print(df)

          praveenmaturi03@gmail.com
0        elkapellypraveen@gmail.com
1     srikanthsatuluri431@gmail.com
2           chanakyanelli@gmail.com
3  yeligetishivakiran2004@gmail.com
4           ajaydasari304@gmail.com
5        smileypraveen412@gmail.com
6      seavanthnelluri609@gmail.com
7             rishivarmaj@gmail.com
8   paanchalaranjithkumar@gmail.com
9    kalavakuripradeep123@gmail.com